server:
  port: 8080

tron:
  private-key: ${TRON_PRIVATE}
  address: ${TRON_ADDRESS}
  full-host: grpc.shasta.trongrid.io:50051
  solidity-node: grpc.shasta.trongrid.io:50052
  contract-path: ${CONTRACT_PATH}